import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

import { Toaster } from "@/components/ui/sonner";
import { Header } from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
	title: "CloudDrive",
	description: "Generated by create next app",
};

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					"min-h-[100dvh] bg-background font-sans antialiased flex flex-col items-center px-4",
					fontSans.variable,
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Header />
					<div className="flex-1 max-w-screen-lg w-full">{children}</div>
					<Footer />
					<Toaster richColors />
				</ThemeProvider>
			</body>
		</html>
	);
}
